name: Dispatch release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        env:
          PAT_USERNAME: ${{ secrets.PAT_USERNAME}}
          PAT_WORKFLOW_TOKEN: ${{ secrets.PAT_WORKFLOW_TOKEN}}
          RELEASE_REF: ${{ github.ref }}
        run: |
          curl -XPOST -u "$PAT_USERNAME:$PAT_WORKFLOW_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/das-l/workflow-test-target/dispatches --data '{"event_type": "release", "client_payload": {"ref": "$RELEASE_REF"}}'
