name: Greet Everyone
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: Trigger repository_dispatch
        env:
          PAT_USERNAME: ${{ secrets.PAT_USERNAME}}
          PAT_WORKFLOW_TOKEN: ${{ secrets.PAT_WORKFLOW_TOKEN}}
        run: |
          curl -XPOST -u "$PAT_USERNAME:$PAT_WORKFLOW_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/das-l/workflow-test-target/dispatches --data '{"event_type": "release"}'
